import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author prashant
 */
public class workerdetails extends javax.swing.JFrame {

    /**
     * Creates new form workerdetails
     */
    public workerdetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jt5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jt2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jt3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 255));
        jLabel5.setText("Contact No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 240, -1, -1));

        jt5.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jt5.setForeground(new java.awt.Color(153, 0, 255));
        jt5.setText("  ");
        getContentPane().add(jt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 295, 166, 30));

        jLabel6.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 298, -1, -1));

        jLabel1.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 85, -1, -1));

        jt1.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jt1.setForeground(new java.awt.Color(153, 0, 255));
        jt1.setText("  ");
        getContentPane().add(jt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 65, 175, -1));

        jLabel2.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setText(" ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Marker Felt", 0, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 51));
        jLabel9.setText("Fill Your Details Here");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 0, -1, -1));

        jt2.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jt2.setForeground(new java.awt.Color(153, 0, 255));
        jt2.setText("  ");
        getContentPane().add(jt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 120, 175, -1));

        jButton2.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 255));
        jButton2.setText(" UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 392, -1, -1));

        jLabel3.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 255));
        jLabel3.setText("Aadhar number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 130, -1, -1));

        jButton3.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 255));
        jButton3.setText(" NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 392, -1, -1));

        jt3.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jt3.setForeground(new java.awt.Color(153, 0, 255));
        jt3.setText("  ");
        getContentPane().add(jt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 185, 175, -1));

        jButton4.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 255));
        jButton4.setText(" DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 392, -1, -1));

        jLabel4.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 255));
        jLabel4.setText("Police Verification Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 190, -1, -1));

        jt4.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jt4.setForeground(new java.awt.Color(153, 0, 255));
        jt4.setText("  ");
        getContentPane().add(jt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(545, 240, 170, 27));

        jButton1.setFont(new java.awt.Font("Kokonor", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 255));
        jButton1.setText("PREVIOUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 392, -1, -1));

        jButton5.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jButton5.setText(" save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 465, 390, 50));

        jButton6.setFont(new java.awt.Font("Marker Felt", 0, 24)); // NOI18N
        jButton6.setText(" Reset");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, 310, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue-strings.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 800, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int ans=JOptionPane.showConfirmDialog(null,"Surely you want to update");
        if(ans==JOptionPane.YES_OPTION)
        {
            try{
                Class.forName("java.sql.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel24x7","root","root");
                Statement st=con.createStatement();
                String q="Update hotel24x7 SET Customer_id= '"+jt2.getText()+"',Name='"+jt1.getText()+"',Aadhar_no= '" +jt2.getText()+"' ,Pan_no='"+jt3.getText()+"',Add_person='"+jt4.getText()+"',Phone_no='"+jt5.getText()+"' WHERE No_of_person= " +jt1.getText()+";";
                st.executeUpdate(q);
                JOptionPane.showMessageDialog(this,"Data UPDATED successfully");
                con.close();
                st.close();
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,"error");
            }
            jt1.setText("");
            jt2.setText("");
            jt1.setText("");
            jt2.setText("");
            jt3.setText("");
            update.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        new jf4().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hire","root","root");
            Statement st=con.createStatement();
            String q="delete from hire where Aadhar_number="+jt2.getText()+";";
            st.executeUpdate(q);
            JOptionPane.showMessageDialog(this,"Data deleted successfully");
            con.close();
            st.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this,"error");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new jf1().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try
        {
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hire","root","root");
            Statement st= con.createStatement();
            String p="Insert into hire values("+jt1.getText()+",'"+jt2.getText()+"','"+jt1.getText()+"','"+jt2.getText()+"','"+jt3.getText()+"','"+jt4.getText()+"','"+jt5.getText()+"');";
            st.executeUpdate(p);
            JOptionPane.showMessageDialog(this,"Data saved successfully");
            con.close();
            st.close();
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this,"error");
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jt1.setText(" ");
        jt2.setText(" ");
        jt1.setText(" ");
        jt2.setText(" ");
        jt3.setText(" ");
        jt4.setText(" ");
        jt5.setText(" ");
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(workerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(workerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(workerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(workerdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new workerdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    // End of variables declaration//GEN-END:variables
}
